### ISSUE TITLE
Pelorus only works with images referenced by sha256

### ISSUE THREAD

**Issue by dandan2000** [konveyor/pelorus#437] opened 2022-04-27 02:48 UTC
Openshift support two ways of referencing images in deployments:

- sha256 
- tag
 
But Pelorus only works with images referenced by sha256.

Example log:

04-26-2022 20:43:04 DEBUG    Getting Replicas for pod: 
project-testn-58cb6d9f6-tqh52 in namespace: project-testn-develop
04-26-2022 20:43:04 DEBUG    Getting replica: project-testn-58cb6d9f6, 
kind: ReplicaSet, namespace: project-testn-develop
04-26-2022 20:43:04 DEBUG    **Skipping unresolved image reference: 
image-registry.openshift-image-registry.svc:5000/project-testn-develop/project-testn:1.0.6**
04-26-2022 20:43:04 DEBUG    Getting Replicas for pod: 
project-daniel-18-msqsc in namespace: prueba-dc

previous lines show log using image:tag .... this way the collector doesn't works

but if I change deployment to image:sha256... it works right.

image-registry.openshift-image-registry.svc:5000/project-testn-develop/project-testn@sha256:a4bfe2f4f8982c8d88043f9d79855163db77e3bcb28196744b1578bf359fb6f3

Pelorus should support both sha256 or tag.

**Comment by KevinMGranger** [comment] 2022-04-27 16:04
We can't rely on tags because they aren't immutable. The sha is the only way to reliably reference an image.

However, an upcoming release will [support getting the sha from `containerStatus` data](https://github.com/konveyor/pelorus/pull/395).

(closing as duplicate of https://github.com/konveyor/pelorus/issues/330, and because it's fixed in master.)

**Closed by KevinMGranger** 2022-04-27 16:04 UTC
