### ISSUE TITLE
Metric Deployment Frequency is not correct in the selected time range

### ISSUE THREAD

**Issue by damianlezcano** [konveyor/pelorus#245] opened 2021-02-03 16:22 UTC
Yesterday (February 1) I built a lab in opentlc (ocp 4.6) and installed pelorus (with helm install ...). and deploys example applications. I deployed example it for the last time at approximately 10pm. Today (February 2), when I select the range "Last 5 minutes" and without having done any deploy, I see the following image:

![Pelorus Dashboard](https://i.imgur.com/MuOJpfS.png)

is it correct?

**Comment by etsauer** [comment] 2021-03-18 15:49
@damianlezcano that sounds like a bug to me. @themoosman @kkoller @malacourse @shaheinm what do you think?

**Comment by damianlezcano** [comment] 2021-04-08 21:14
is there an update on this incident?

**Comment by etsauer** [comment] 2021-05-05 19:24
@damianlezcano sorry, I've been out the last month! We've verified that this is a bug and intend to fix it.

**Comment by etsauer** [comment] 2021-05-05 19:31
So for more info on this... the reason this is happening is that the deploytime exporter scans for deployments in openshift every few minutes, and repeatedly pushes to prometheus all deployments that it finds, and Prometheus sets the timestamp as "time of collection". So basically, Pelorus keeps counting any deployment it finds in openshift over and over again, even if its older.

One hacky way to work around this is to very actively prune your openshift history, but that's not a good solution for everyone. The longer term fix is to figure out how to manipulate timestamps in Prometheus so that we can set the collection timestamp to the `creationTimestamp` of the Pods/Replicasets in the deployment.

**Comment by kkoller** [comment] 2021-05-05 19:35
To add to this discussion, it seems that Prometheus has recently enabled the import of historical data via their 'backfill' utility, described here: https://github.com/prometheus/prometheus/blob/v2.24.0/docs/storage.md#backfilling-from-openmetrics-format

Our initial thought is that changing our exporters to insert the data manually, with the timestamp reflecting the actual deploy time and not the metric collection time, will resolve this issue.

**Comment by KevinMGranger** [comment] 2022-03-17 17:26
I need to double check if this is still an issue.

It appears that [we're _trying_ to pass the timestamp explicitly to the metric](https://github.com/konveyor/pelorus/blob/113dfd8277bd2386e26426503b461f268202520f/exporters/deploytime/app.py#L52-L54). What we're actually setting is the `value`. You can also set a timestamp. I'll also need to double-check which queries are using the value versus the timestamp.

**Comment by weshayutin** [comment] 2022-06-09 15:59
I can confirm this is in fact a bug..  The timestamp used by the query in prometheus does not appear to be the timestamp of the deployment but the last update from prometheus.

deploy_timestamp{app="todolist", container="deploytime-exporter", endpoint="http", exported_namespace="mongo-persistent", image_sha="sha256:36c463606ec968503045fb68f4c54d1bca8f48cbe258f45c3552d5860ad7fa57", instance="10.128.2.178:8080", job="deploytime-exporter", namespace="pelorus", pod="deploytime-exporter-1-hg7rs", service="deploytime-exporter"}
1654710780 @1654789806.268
1654710780 @1654789836.268
1654710780 @1654789866.268
1654710780 @1654789896.268
1654710780 @1654789926.268
1654710780 @1654789956.268
1654710780 @1654789986.268
1654710780 @1654790016.268
1654710780 @1654790046.268
1654710780 @1654790076.268

so instead of 1654710780 being used, "@1654789806.268" is used

Queries:
count_over_time(deploy_timestamp[30s])
deploy_timestamp{app="todolist"}[5m]

**Comment by weshayutin** [comment] 2022-06-09 16:23
![Screenshot from 2022-06-09 10-22-26](https://user-images.githubusercontent.com/138787/172896535-3fef6d41-0a99-4b7b-b501-abc64427b3ad.png)

**Comment by weshayutin** [comment] 2022-06-09 16:24
also seems like this is addressed in the golang client, but I haven't found how to override the timestamp with python yet.
FYI https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#NewMetricWithTimestamp

**Comment by weshayutin** [comment] 2022-06-09 17:43
ya.. looks like when the deploytime metric is added.. the timestamp is set to None.
)
(Pdb) self.samples
[Sample(name='deploy_timestamp', labels={'namespace': 'mongo-persistent', 'app': 'todolist', 'image_sha': 'sha256:36c463606ec968503045fb68f4c54d1bca8f48cbe258f45c3552d5860ad7fa57'}, value=1654710780.0, timestamp=None, exemplar=None)]
(Pdb)

**Comment by weshayutin** [comment] 2022-06-09 18:27
![Screenshot from 2022-06-09 12-25-57](https://user-images.githubusercontent.com/138787/172918403-4cfd1899-3efc-4b77-9b83-a0617ffa97
![Screenshot from 2022-06-09 12-26-25](https://user-images.githubusercontent.com/138787/172918432-9778033c-ee64-466b-a5a5-93c79babcf57.png)
8b.png)

**Comment by weshayutin** [comment] 2022-06-09 18:28
![Screenshot from 2022-06-09 12-25-57](https://user-images.githubusercontent.com/138787/172918733-e2fe0427-8a35-4d6a-96e0-0e4a442a14bb.png)

**Comment by weshayutin** [comment] 2022-06-09 18:29
![Screenshot from 2022-06-09 12-25-57](https://user-images.githubusercontent.com/138787/172918877-3a0b9a54-7f24-4815-ac24-05a0d8839f45.png)

OK.. deploy the app, and wait a few minutes

**Comment by weshayutin** [comment] 2022-06-09 18:30
after a few minutes...
set the time to n - 1 minute
![Screenshot from 2022-06-09 12-26-25](https://user-images.githubusercontent.com/138787/172919071-d7d1b276-8df6-4cfd-9b78-e6ff33db7b38.png)

**Closed** 2022-06-21 21:55 UTC
Labels: kind/bug, Priority 1, Size Large, needs investigation, mvr, bd-1
